version: '3'
services:
    python_docker_sample:
        container_name: 'python_docker_sample'
        user: 1000:1000
        build:
            context: ./
            args:
                UID: 1000
                USERNAME: htakeuchi0
                PYTHONDIR: python_docker_sample
        tty: true
        working_dir: '/home/htakeuchi0/python_docker_sample'
        volumes:
            - ./sandbox:/home/htakeuchi0/python_docker_sample/sandbox:Z
            - ./tests:/home/htakeuchi0/python_docker_sample/tests:Z

